#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &

# for 7567 with built-in screen
xrandr --output HDMI-1-0 --primary --mode 1920x1080 --rotate normal --output eDP1 --mode 1920x1080 --rotate normal --left-of HDMI-1-0

# for 7567 w/0 built-in screen
#xrandr --output HDMI-1-1 --primary --mode 1920x1080 --rotate normal

# for AMD PC
#xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal

feh --bg-fill /home/kesav/Pictures/Wallpapers/wal.png

picom &

# for 7567 with built-in screen
bspc monitor HDMI-1-0 -d I II III IV V
bspc monitor eDP1 -d VI VII VIII IX

bspc config border_width         0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Remove x cursor
xsetroot -cursor_name left_ptr &

# Launch polybar
$HOME/.config/polybar/launch.sh