#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &

$HOME/.config/polybar/launch.sh

feh --bg-fill /home/kesav/Pictures/Wallpapers/wal.png

picom &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


bspc config border_width         0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
#bspc config top_padding 20
bspc config top_padding 40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Remove x cursor
xsetroot -cursor_name left_ptr &
